workflow "CICD Workflow" {
  on = "push"
  resolves = ["SNS Notification"]
}

- name: Login to ECR
  id: ecr
  uses: jwalton/gh-ecr-login@v1
  with:
    access-key-id: AKIAQDLEQGJPCQ6W6ACJ
    secret-access-key: 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
    region: ap-south-1
- name: Push to ECR
  run: |
    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 007190098526.dkr.ecr.ap-south-1.amazonaws.com
    docker build -t cognavi-user-management 
    docker tag cognavi-user-management:latest 007190098526.dkr.ecr.ap-south-1.amazonaws.com/cognavi-user-management:latest
    docker push 007190098526.dkr.ecr.ap-south-1.amazonaws.com/cognavi-user-management:latest
