workflow "CICD Workflow" {
  on = "push"
  resolves = ["SNS Notification"]
}

action "ECR Login" {
  needs: ["Build Image"]
  env = {
    AWS_DEFAULT_REGION = "ap-south-1"
    AWS_REGION = "$AWS_DEFAULT_REGION"
  }
  runs = ["/bin/sh", "-c", "aws ecr get-login --no-include-email | sh"]
  secrets = [
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
  ]
}
